# Actions train a model on Azure Machine Learning
name: test-workflow

on: workflow_dispatch
  #push:
    #branches:
    #  - master
    # paths:
    #   - 'code/*'

jobs:
  train:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
        
    
    - name: Test Command Line
      run: echo "Inside Step 2"
    
    - name: Present working directory
      run: pwd
      
    - name: List files in the directory
      run: ls
      
    - name: List files in the directory
      run: dir
